In [4]:
import pandas as pd

In [5]:
holders_df = pd.read_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/data/holders.csv')
benefical_filings_df = pd.read_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/data/beneficial_filings.csv')
opening_postions_df = pd.read_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/data/opening_positions.csv')
register_events_df = pd.read_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/data/register_events.csv')
shares_outstanding_df = pd.read_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/data/shares_outstanding.csv')

In [6]:
holders_df

,holder_id,version,valid_from,holder_name,holder_type,country
0,H001,1,2026-01-01,CEDE & CO,nominee,US
1,H002,1,2026-01-01,Marisol Vance,individual,US
2,H003,1,2026-01-01,Ridgeline Capital Partners LP,institution,US
3,H004,1,2026-01-01,Northwind Metals Employee Stock Trust,trust,US
4,H005,1,2026-01-01,Tobias Kell,insider,US
5,H006,1,2026-01-01,Anouk de Vries,individual,NL
6,H007,1,2026-01-01,Halvard Family Holdings LLC,institution,US
7,H008,1,2026-01-01,Priya Raghunathan,individual,US
8,H009,1,2026-01-01,Bluewater Pension Trust,institution,CA
9,H010,1,2026-01-01,Owen Castellanos,individual,US
10,H011,1,2026-01-01,Sable Point Advisors LLC,institution,US
11,H012,1,2026-01-01,Dmitri Volkov,individual,US
12,H010,2,2026-07-15,Owen Castellanos,insider,US
13,H007,2,2026-08-03,Halvard Family Office LLC,institution,US

In [10]:
opening_postions_df

    as_of_date holder_id    shares
0   2026-05-31      H001  33155500
1   2026-05-31      H002    120000
2   2026-05-31      H003   2900000
3   2026-05-31      H004   1450000
4   2026-05-31      H005    610000
5   2026-05-31      H006     45000
6   2026-05-31      H007    880000
7   2026-05-31      H008     60000
8   2026-05-31      H009   1020000
9   2026-05-31      H010    210000
10  2026-05-31      H011         0
11  2026-05-31      H012     32000

In [6]:
register_events_df

,event_id,transfer_id,event_type,from_holder_id,to_holder_id,shares,effective_date,recorded_at,reverses_transfer_id,note
0,E1001,T5002,transfer,H008,H001,100,2026-06-01,2026-06-01 10:46:00,NaN,NaN
1,E1002,T5003,transfer,H003,H001,12000,2026-06-01,2026-06-01 15:54:00,NaN,NaN
2,E1000,T5001,transfer,H001,H006,100,2026-06-01,2026-06-01 17:04:00,NaN,NaN
3,E1003,T5004,transfer,H008,H001,1000,2026-06-02,2026-06-02 11:55:00,NaN,NaN
4,E1004,T5005,transfer,H008,H001,1000,2026-06-03,2026-06-03 15:10:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
189,E1175,T5176,transfer,H002,H001,12000,2026-08-28,2026-08-28 10:43:00,NaN,NaN
190,E1176,T5177,transfer,H012,H001,1000,2026-08-31,2026-08-31 09:06:00,NaN,NaN
191,E1177,T5178,transfer,H008,H001,1000,2026-08-31,2026-08-31 10:08:00,NaN,NaN
192,E1178,T5179,transfer,H001,H008,250,2026-08-31,2026-08-31 14:03:00,NaN,NaN
193,E1189,T5190,reversal,H012,H001,12000,2026-08-27,2026-09-02 10:15:00,T5189,duplicate instruction

In [12]:
shares_outstanding_df

   as_of_date  shares_outstanding source_form published_date
0  2026-03-31            40482500        10-Q     2026-05-08
1  2026-06-30            40782500        10-Q     2026-08-07
2  2026-08-03            39882500         8-K     2026-08-05

In [12]:
benefical_filings_df

,accession_no,form_type,filer_name,filer_cik,filing_date,event_date,shares_reported,percent_reported,outstanding_basis,amends_accession_no
0,0001234567-26-000101,SC 13G,"Ridgeline Capital Partners, L.P.",1234567,2026-02-13,2025-12-31,2900000,7.16,40482500,NaN
1,0001234567-26-000188,SC 13G/A,Ridgeline Capital Partners LP,1234567,2026-07-10,2026-06-30,4300000,10.62,40482500,0001234567-26-000101
2,0002233445-26-000042,SC 13G,Bluewater Pension Trust,2233445,2026-02-14,2025-12-31,2150000,5.31,40482500,NaN
3,0002233445-26-000077,SC 13G/A,Bluewater Pension Trust,2233445,2026-08-28,2026-08-19,1130000,2.83,39882500,0002233445-26-000042
4,0003344556-26-000009,SC 13G,Sable Point Advisors LLC,3344556,2026-07-17,2026-07-07,2100000,5.15,40782500,NaN
5,0003344556-26-000015,SC 13D,Sable Point Advisors LLC,3344556,2026-08-07,2026-07-28,3750000,9.20,40782500,0003344556-26-000009
6,0003344556-26-000019,SC 13D/A,"Sable Point Advisors, LLC",3344556,2026-08-21,2026-08-06,3350000,8.40,39882500,0003344556-26-000015
7,0004455667-26-000031,SC 13G,Halvard Family Office LLC,4455667,2026-08-12,2026-07-30,2200000,5.39,40782500,NaN
8,0005566778-26-000003,SC 13D,Tobias Kell,5566778,2026-01-22,2026-01-15,2610000,6.45,40482500,NaN
9,0005566778-26-000008,SC 13D/A,Tobias Kell,5566778,2026-08-25,2026-08-11,2460000,6.17,39882500,0005566778-26-000003
10,0006677889-26-000120,SC 13G,Vantage Quant Strategies Ltd,6677889,2026-06-05,2026-05-29,2050000,5.06,40482500,NaN
11,0006677889-26-000141,SC 13G/A,Vantage Quant Strategies Ltd,6677889,2026-06-19,2026-06-12,1900000,4.69,40482500,0006677889-26-000120
12,0006677889-26-000160,SC 13G/A,Vantage Quant Strategies Ltd,6677889,2026-07-24,2026-07-15,2300000,5.68,40482500,0006677889-26-000141
13,0002233445-26-000077,SC 13G/A,Bluewater Pension Trust,2233445,2026-08-28,2026-08-19,1130000,2.83,39882500,0002233445-26-000042

In [10]:
# check duplicate event id in register_events
register_events_df[register_events_df.duplicated(subset=['event_id'], keep=False)]

,event_id,transfer_id,event_type,from_holder_id,to_holder_id,shares,effective_date,recorded_at,reverses_transfer_id,note
40,E1040,T5041,transfer,H002,H001,2500,2026-06-23,2026-06-23 12:35:00,NaN,NaN
41,E1040,T5041,transfer,H002,H001,2500,2026-06-23,2026-06-23 12:35:00,NaN,NaN

Data error:register events file has a duplicate record

In [11]:
register_events_df.drop_duplicates(subset=['event_id'],inplace=True)
register_events_df.to_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/clean_data/register_events.csv', index=False)

In [13]:
#check duplicates in  beneficial filings
benefical_filings_df[benefical_filings_df.duplicated(subset=['accession_no'], keep=False)]

,accession_no,form_type,filer_name,filer_cik,filing_date,event_date,shares_reported,percent_reported,outstanding_basis,amends_accession_no
3,0002233445-26-000077,SC 13G/A,Bluewater Pension Trust,2233445,2026-08-28,2026-08-19,1130000,2.83,39882500,0002233445-26-000042
13,0002233445-26-000077,SC 13G/A,Bluewater Pension Trust,2233445,2026-08-28,2026-08-19,1130000,2.83,39882500,0002233445-26-000042

In [14]:
#remove duplicate records
benefical_filings_df.drop_duplicates(subset=['accession_no'], inplace=True)
benefical_filings_df.to_csv('/Users/akhilesh/Desktop/Shareholder_Intelligence_TakeHome/clean_data/beneficial_filings.csv', index=False)